# Generated by Django 5.1.6 on 2025-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
