# Generated by Django 5.1.6 on 2025-04-02 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_activation_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gst', models.CharField(max_length=15, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('hsn_codes', models.JSONField(default=list)),
                ('organization', models.CharField(max_length=255)),
                ('contact_mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
