# Generated by Django 5.1.6 on 2025-04-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userformdata_last_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationOTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_token', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activation OTP',
                'verbose_name_plural': 'Activation OTPs',
            },
        ),
    ]
