# Generated by Django 5.1.6 on 2025-04-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformdata',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
