# Generated by Django 5.1.6 on 2025-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_organization_member_page_organizationmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='password',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='temp_password',
            field=models.CharField(blank=True, help_text="Set initial password (won't be stored after save)", max_length=128, verbose_name='Initial Password'),
        ),
    ]
