# Generated by Django 5.1.6 on 2025-02-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_eventspage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect user when they click the event button.', null=True),
        ),
    ]
