# Generated by Django 5.1.6 on 2025-02-25 04:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventspage_iess_body_eventspage_inee_body_iess_inee'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='awards_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='Awards_Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('places', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('EASTERN', 'Eastern'), ('WESTERN', 'Western'), ('NORTHERN', 'Northern'), ('SOUTHERN', 'Southern')], default='NORTHERN', max_length=10)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_awards', to='home.eventspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webinar_Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_webinar', to='home.eventspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
