# Generated by Django 5.1.6 on 2025-02-25 05:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_eventspage_awards_body_awards_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('heading', models.CharField(max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_image', to='home.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_events', to='home.eventspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
