# Generated by Django 5.1.6 on 2025-03-21 05:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_membershippage_committeememeber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeememeber',
            name='designation',
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('member', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='home.committeememeber')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
