# Generated by Django 5.1.6 on 2025-03-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_committeememeber_designation_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeememeber',
            name='subname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
