# Generated by Django 5.1.6 on 2025-03-26 07:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_committeememeber_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(height_field='height', storage=storages.backends.s3.S3Storage(), upload_to='images/', verbose_name='file', width_field='width'),
        ),
    ]
